#!/bin/bash

site=www.jsmenagerie.com

myarg="$1"
if [ $myarg = "all" ]
then
  s3cmd put *.css s3://$site --acl-public
  s3cmd put --recursive jsfiles s3://$site --acl-public
  s3cmd put *.html s3://$site --acl-public
  exit
fi

if [ $myarg = "html" ]
then
  s3cmd put --recursive *.html s3://$site --acl-public
  exit
fi

s3cmd put --recursive $myarg s3://$site/$myarg --acl-public
