#!/bin/bash

site=www.jsmenagerie.com

myarg="$1"
if [ $myarg = "all" ]
then
  echo 'foo'
  s3cmd put *.css s3://$site --acl-public
  s3cmd put *.js s3://$site --acl-public
  s3cmd put --recursive jquery s3://$site --acl-public
  s3cmd put *.html s3://$site --acl-public
  exit
elif [ $myarg = "libs" ]
then
  s3cmd put --recursive libs s3://$site --acl-public
else
  s3cmd put --recursive $myarg s3://$site/$myarg --acl-public
fi
